import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { ROUTE_CONTRACT, TARGET_IA_TOP_LEVEL } from './route-contract';
import { getNavRoot, routeNavRoot } from './route-nav-map';
import { getAllNavItems } from './app-nav-items';
import { registeredRoutePaths, topLevelRoutePaths } from './route-tree-paths';

function hasRoutePath(path: string): boolean {
  return registeredRoutePaths().includes(path);
}

/**
 * Every retired legacy route below must stay unregistered. They used to be
 * redirect stubs for capabilities that now have exactly one canonical hub
 * destination; internal code never generates them.
 */
const RETIRED_ROUTE_PATHS = [
  '/landing',
  '/units',
  '/utilities',
  '/documents-vault',
  '/finance/collections',
  '/finance/expenses',
  '/finance/deposits',
  '/finance/banking',
  '/invoices',
  '/expenses',
  '/arrears',
  '/deposits',
  '/owner-settlements',
  '/bank-reconciliation',
  '/accounting',
  '/automation',
  '/system',
  '/audit-log',
  '/data-integrity',
  '/change-password',
] as const;

describe('route-contract — single source of truth', () => {
  it('every canonical in contract is registered in route-tree.ts', () => {
    for (const entry of ROUTE_CONTRACT) {
      expect(hasRoutePath(entry.canonical), `canonical ${entry.canonical} not in route-tree`).toBe(true);
    }
  });

  it('retired legacy routes are no longer registered', () => {
    for (const path of RETIRED_ROUTE_PATHS) {
      expect(hasRoutePath(path), `retired route ${path} must not be registered`).toBe(false);
    }
  });

  it('retired legacy routes are not generated by internal navigation', () => {
    const retiredAsLiteral = new Set(RETIRED_ROUTE_PATHS.map((path) => `'${path}'`));
    const offenders = new Set<string>();
    for (const file of [
      'features/dashboard/needs-attention-signal.ts',
      'features/ai-assistant/ai-assistant-navigation.ts',
      'features/financials/invoices/quick-collect.ts',
      'features/command-palette/use-command-search.ts',
    ]) {
      const source = readFileSync(new URL(`../../${file}`, import.meta.url), 'utf8');
      for (const path of retiredAsLiteral) {
        if (source.includes(path)) offenders.add(`${file} -> ${path}`);
      }
    }
    expect(offenders.size, [...offenders].join('\n')).toBe(0);
  });

  it('has no duplicate canonical entries', () => {
    const canonicals = ROUTE_CONTRACT.map((e) => e.canonical);
    expect(new Set(canonicals).size).toBe(canonicals.length);
  });

  it('all sidebarRoot values exist in routeNavRoot values', () => {
    const knownRoots = new Set(routeNavRoot.values());
    for (const entry of ROUTE_CONTRACT) {
      if (['/', '/login', '/privacy', '/terms', '/support', '/dev/design-system'].includes(entry.canonical)) continue;
      expect(knownRoots.has(entry.sidebarRoot), `unknown sidebarRoot ${entry.sidebarRoot} for ${entry.canonical}`).toBe(true);
    }
  });

  it('every non-public canonical maps correctly via getNavRoot', () => {
    for (const entry of ROUTE_CONTRACT) {
      if (['/', '/login', '/privacy', '/terms', '/support'].includes(entry.canonical)) continue;
      const testPath = entry.canonical.replace(/\$[^/]+/g, '_id');
      expect(getNavRoot(testPath)).toBe(entry.sidebarRoot);
    }
  });

  it('pins exactly seven target IA roots', () => {
    expect(TARGET_IA_TOP_LEVEL).toEqual([
      '/dashboard',
      '/properties',
      '/contracts',
      '/financials',
      '/maintenance',
      '/reports',
      '/settings',
    ]);
    const canonicals = new Set(ROUTE_CONTRACT.map((e) => e.canonical));
    for (const path of TARGET_IA_TOP_LEVEL) {
      expect(canonicals.has(path), `target IA path ${path} missing from contract`).toBe(true);
      expect(ROUTE_CONTRACT.find((entry) => entry.canonical === path)?.isPrimaryNav).toBe(true);
    }
  });

  it('all visible nav items have a contract entry', () => {
    const navPaths = new Set(getAllNavItems().map(([to]) => to));
    for (const path of navPaths) {
      expect(ROUTE_CONTRACT.some((e) => e.canonical === path), `nav path ${path} missing in contract`).toBe(true);
    }
  });

  it('every contract entry has an Arabic title', () => {
    for (const entry of ROUTE_CONTRACT) {
      expect(entry.titleAr).toMatch(/[\u0600-\u06FF]/);
    }
  });

  it('keeps secondary entities canonical but not global', () => {
    const expectedRoots: Record<string, string> = {
      '/owners': '/properties',
      '/lands': '/properties',
      '/tenants': '/contracts',
      '/people': '/contracts',
      '/leads': '/contracts',
      '/communication': '/contracts',
      '/commissions': '/financials',
      '/receipts': '/financials',
    };

    for (const [path, root] of Object.entries(expectedRoots)) {
      const entry = ROUTE_CONTRACT.find((candidate) => candidate.canonical === path)!;
      expect(entry.isPrimaryNav).toBe(false);
      expect(entry.sidebarRoot).toBe(root);
    }
  });

  it('registers no duplicate top-level path', () => {
    const paths = topLevelRoutePaths();
    expect(new Set(paths).size).toBe(paths.length);
  });
});
