/**
 * Canonical Arabic terminology for navigation and workspace surfaces.
 * Visible navigation must never fall back to English merely because a company
 * locale is configured as English; the current MALEK shell is Arabic-first.
 */

/** Canonical Arabic label for every primary/mobile navigation labelKey. */
export const navigationLabels: Readonly<Record<string, string>> = {
  dashboard: 'لوحة التحكم',
  properties: 'العقارات',
  owners: 'الملاك',
  tenants: 'المستأجرون',
  contracts: 'العقود',
  maintenance: 'التشغيل والصيانة',
  financials: 'المالية',
  financialOverview: 'المالية',
  accountingReports: 'المحاسبة والتقارير',
  reports: 'المحاسبة والتقارير',
  reportsAndStatements: 'المحاسبة والتقارير',
  aiAssistant: 'المساعد الذكي',
  settings: 'الإعدادات',
  peopleDirectory: 'جهات التعامل',
  units: 'الوحدات',
  lands: 'الأراضي',
  leads: 'العملاء المحتملون',
  communication: 'التواصل والمتابعات',
  utilities: 'المرافق',
  automation: 'الأتمتة',
  documentsVault: 'خزينة المستندات',
  changePassword: 'تغيير كلمة المرور',
  auditLog: 'سجل التدقيق',
  dataIntegrity: 'سلامة البيانات',
  system: 'إدارة النظام',
  newContract: 'عقد جديد',
  newProperty: 'عقار جديد',
  newPerson: 'شخص جديد',
};

/** Canonical Arabic workspace label for secondary items. */
export const workspaceLabels: Record<string, string> = {
  owners: 'الملاك',
  units: 'الوحدات',
  lands: 'الأراضي',
  people: 'جهات التعامل',
  tenants: 'المستأجرون',
  leads: 'العملاء المحتملون',
  communication: 'التواصل والمتابعات',
  utilities: 'المرافق',
  automation: 'الأتمتة',
  documents_vault: 'خزينة المستندات',
  invoices: 'الفواتير',
  receipts: 'الإيصالات',
  expenses: 'المصروفات',
  arrears: 'المتأخرات',
  deposits: 'التأمينات',
  owner_settlements: 'تسويات الملاك',
  bank_reconciliation: 'المطابقة البنكية',
  commissions: 'العمولات',
  aiAssistant: 'المساعد الذكي',
  changePassword: 'تغيير كلمة المرور',
  auditLog: 'سجل التدقيق',
  dataIntegrity: 'سلامة البيانات',
  system: 'إدارة النظام',
};

export const hubPageTitles: Record<string, string> = {
  '/dashboard': 'لوحة التحكم',
  '/properties': 'العقارات',
  '/properties/new': 'إضافة عقار',
  '/properties/$propertyId': 'تفاصيل العقار',
  '/properties/$propertyId/edit': 'تعديل عقار',
  '/owners': 'الملاك',
  '/owners/$ownerId': 'ملف المالك',
  '/tenants': 'المستأجرون',
  '/contracts': 'العقود',
  '/contracts/new': 'إنشاء عقد',
  '/contracts/$contractId': 'تفاصيل العقد',
  '/contracts/$contractId/edit': 'تعديل عقد',
  '/maintenance': 'التشغيل والصيانة',
  '/financials': 'المالية',
  '/finance/collections': 'التحصيل والفواتير',
  '/finance/expenses': 'المصروفات والمتأخرات',
  '/finance/deposits': 'التأمينات وتسويات الملاك',
  '/finance/banking': 'البنوك والعمولات',
  '/invoices': 'الفواتير',
  '/receipts': 'الإيصالات',
  '/expenses': 'المصروفات',
  '/arrears': 'المتأخرات',
  '/deposits': 'التأمينات',
  '/owner-settlements': 'تسويات الملاك',
  '/bank-reconciliation': 'المطابقة البنكية',
  '/commissions': 'العمولات',
  '/reports': 'المحاسبة والتقارير',
  '/accounting': 'المحاسبة والتقارير',
  '/settings': 'الإعدادات',
  '/ai-assistant': 'المساعد الذكي',
  '/people': 'جهات التعامل',
  '/leads': 'العملاء المحتملون',
  '/communication': 'التواصل والمتابعات',
  '/utilities': 'المرافق',
  '/automation': 'الأتمتة',
  '/documents-vault': 'خزينة المستندات',
  '/units': 'الوحدات',
  '/lands': 'الأراضي',
  '/change-password': 'تغيير كلمة المرور',
  '/audit-log': 'سجل التدقيق',
  '/data-integrity': 'سلامة البيانات',
  '/system': 'إدارة النظام',
};

export const canonicalTerms = {
  expenses: 'المصروفات',
  receipts: 'الإيصالات',
  arrears: 'المتأخرات',
  deposits: 'التأمينات',
  tenants: 'المستأجرون',
  owners: 'الملاك',
  invoices: 'الفواتير',
  commissions: 'العمولات',
  bankReconciliation: 'المطابقة البنكية',
  ownerSettlements: 'تسويات الملاك',
} as const;
