// S08 test fixtures — Demo literals live ONLY here, never in production migration/scripts
export const S08_FIXTURE_COMPANIES = [
  { id: '00000000-0000-4000-a000-000000000001', name: 'Demo Malek Co A' },
  { id: '00000000-0000-4000-a000-000000000002', name: 'Demo Malek Co B' },
] as const;

export const S08_FIXTURE_PERIODS = [
  { id: 'p-2026-01', name: '2026-01' },
  { id: 'p-2026-02', name: '2026-02' },
] as const;

export const S08_FIXTURE_FINDING_CODES = [
  'DUPLICATE_PAYMENT_ACROSS_SETTLEMENTS',
  'DUPLICATE_EXPENSE_ACROSS_SETTLEMENTS',
  'PAID_SETTLEMENT_WITHOUT_PAYMENT_EVIDENCE',
  'OWNER_TENANT_EXPENSE_IN_OFFICE_ACCOUNT',
  'MISSING_BENEFICIARY',
  'DEDUCTION_WITHOUT_BENEFICIARY',
  'DEDUCTION_WITHOUT_APPROVED_CLAIM',
  'REFUND_EXCEEDING_AVAILABLE_BALANCE',
  'SOURCE_WITHOUT_POSTING',
  'POSTING_WITHOUT_SOURCE',
  'VOIDED_SURVIVING_POSTING',
  'REVERSAL_WITHOUT_ORIGINAL',
  'RETROACTIVE_COMMISSION_CHANGE',
  'MASTER_LEASE_MISSING_DISCOUNT_RATE',
  'SUBLEDGER_GL_MISMATCH',
] as const;
