import type { AppPermission } from '@/features/auth/permissions';
import {
  LayoutDashboard,
  Users,
  Building2,
  FileText,
  ShieldCheck,
  Landmark,
  FileSpreadsheet,
  ReceiptText,
  ClipboardList,
  WalletCards,
  FileCheck,
  HandCoins,
  Settings,
  Building,
  KeyRound,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export interface StaticCommand {
  id: string;
  title: string;
  category: 'navigation' | 'financial' | 'operational' | 'system';
  canonicalRoute: string;
  search?: Record<string, string>;
  permission: AppPermission | null;
  keywords: string[];
  icon: LucideIcon;
}

export const STATIC_COMMANDS: StaticCommand[] = [
  {
    id: 'dashboard',
    title: 'لوحة التحكم (الرئيسية)',
    category: 'navigation',
    canonicalRoute: '/dashboard',
    permission: null,
    keywords: ['الرئيسية', 'لوحة التحكم', 'dashboard', 'home', 'الاحصائيات'],
    icon: LayoutDashboard,
  },
  {
    id: 'people',
    title: 'الأشخاص (جهات التعامل)',
    category: 'navigation',
    canonicalRoute: '/people',
    permission: null,
    keywords: ['الأشخاص', 'العملاء', 'جهات التعامل', 'مستأجرين', 'ملاك', 'people', 'contacts'],
    icon: Users,
  },
  {
    id: 'properties',
    title: 'العقارات',
    category: 'navigation',
    canonicalRoute: '/properties',
    permission: null,
    keywords: ['العقارات', 'عقار', 'مباني', 'شقق', 'properties', 'real estate'],
    icon: Building2,
  },
  {
    id: 'lands',
    title: 'الأراضي',
    category: 'navigation',
    canonicalRoute: '/lands',
    permission: 'lands.view',
    keywords: ['الأراضي', 'أرض', 'قطع الأراضي', 'lands', 'plots'],
    icon: Building,
  },
  {
    id: 'contracts',
    title: 'العقود الإيجارية',
    category: 'navigation',
    canonicalRoute: '/contracts',
    permission: null,
    keywords: ['العقود', 'عقد إيجار', 'التأجير', 'contracts', 'leases'],
    icon: FileText,
  },
  {
    id: 'owners',
    title: 'الملاك',
    category: 'navigation',
    canonicalRoute: '/owners',
    permission: 'owners.hub.view',
    keywords: ['الملاك', 'المالك', 'أصحاب الأملاك', 'owners'],
    icon: Users,
  },
  {
    id: 'tenants',
    title: 'المستأجرون',
    category: 'navigation',
    canonicalRoute: '/tenants',
    permission: null,
    keywords: ['المستأجرون', 'المستأجر', 'النزلاء', 'tenants'],
    icon: KeyRound,
  },
  {
    id: 'commissions',
    title: 'العمولات',
    category: 'navigation',
    canonicalRoute: '/commissions',
    permission: 'commissions.view',
    keywords: ['العمولات', 'عمولة التسويق', 'عمولة التحصيل', 'commissions'],
    icon: HandCoins,
  },
  {
    id: 'maintenance',
    title: 'الخدمات (التشغيل والصيانة)',
    category: 'navigation',
    canonicalRoute: '/maintenance',
    permission: null,
    keywords: ['الصيانة', 'الخدمات', 'الأعطال', 'طلبات الصيانة', 'maintenance', 'services'],
    icon: Landmark,
  },
  {
    id: 'reports',
    title: 'المحاسبة والتقارير المالية',
    category: 'navigation',
    canonicalRoute: '/reports',
    permission: null,
    keywords: ['التقارير', 'المحاسبة', 'الأستاذ العام', 'كشف الحساب', 'reports', 'accounting'],
    icon: FileSpreadsheet,
  },
  {
    id: 'settings',
    title: 'الإعدادات العامة للنظام',
    category: 'navigation',
    canonicalRoute: '/settings',
    permission: null,
    keywords: ['الإعدادات', 'إعدادات النظام', 'الملف الشخصي', 'settings', 'configuration'],
    icon: Settings,
  },

  // ── Financial subviews inside /financials
  {
    id: 'financial-invoices',
    title: 'المالية — الفواتير والتحصيل',
    category: 'financial',
    canonicalRoute: '/financials',
    search: { section: 'collections', view: 'invoices' },
    permission: null,
    keywords: ['الفواتير', 'التحصيل', 'المالية', 'المطالبات', 'invoices', 'billing'],
    icon: FileSpreadsheet,
  },
  {
    id: 'financial-receipts',
    title: 'المالية — سجل الإيصالات والقبض',
    category: 'financial',
    canonicalRoute: '/financials',
    search: { section: 'collections', view: 'receipts' },
    permission: null,
    keywords: ['الإيصالات', 'سند قبض', 'المدفوعات المستلمة', 'receipts', 'payments'],
    icon: ReceiptText,
  },
  {
    id: 'financial-arrears',
    title: 'المالية — المتأخرات والديون والذمم',
    category: 'financial',
    canonicalRoute: '/financials',
    search: { section: 'collections', view: 'arrears' },
    permission: 'arrears.view',
    keywords: ['المتأخرات', 'الديون', 'أعمار الديون', 'الذمم', 'arrears', 'overdue'],
    icon: ClipboardList,
  },
  {
    id: 'financial-expenses',
    title: 'المالية — المصروفات والمدفوعات',
    category: 'financial',
    canonicalRoute: '/financials',
    search: { section: 'expenses', view: 'expenses' },
    permission: 'expenses.view',
    keywords: ['المصروفات', 'المصاريف', 'التكاليف', 'expenses', 'payables'],
    icon: WalletCards,
  },
  {
    id: 'financial-deposits',
    title: 'المالية — تأمينات المستأجرين (الأمانات)',
    category: 'financial',
    canonicalRoute: '/financials',
    search: { section: 'funds', view: 'deposits' },
    permission: 'financial.deposits.view',
    keywords: ['التأمينات', 'الأمانات', 'الودائع', 'deposits', 'custody'],
    icon: FileCheck,
  },
  {
    id: 'financial-owner-settlements',
    title: 'المالية — تسويات الملاك والمستحقات',
    category: 'financial',
    canonicalRoute: '/financials',
    search: { section: 'funds', view: 'owner_settlements' },
    permission: 'financial.owner_settlements.view',
    keywords: ['تسويات الملاك', 'حساب الملاك', 'المستحقات', 'settlements'],
    icon: HandCoins,
  },
  {
    id: 'financial-bank-reconciliation',
    title: 'المالية — مطابقة كشف الحساب البنكي',
    category: 'financial',
    canonicalRoute: '/financials',
    search: { section: 'banking', view: 'bank_reconciliation' },
    permission: 'financial.bank_reconciliation.view',
    keywords: ['البنوك', 'المطابقة البنكية', 'كشف الحساب', 'reconciliation', 'banking'],
    icon: Landmark,
  },
];
