// Compatibility facade: this module preserves the original public surface of
// the financial reports service. Implementation now lives in domain-specific
// modules under this directory; this file only re-exports so existing
// consumers and RPC names/types are unaffected.
export {
  getBalanceSheetReport,
  getIncomeStatementReport,
  getTrialBalanceReport,
  normalizeBalanceSheetReport,
  normalizeIncomeStatementReport,
  normalizeTrialBalanceReport,
  type BalanceSheetReport,
  type BalanceSheetSectionItem,
  type IncomeStatementLine,
  type IncomeStatementReport,
  type TrialBalanceAccount,
  type TrialBalanceReport,
} from './accounting-reports-service';
export {
  getOwnerStatementReport,
  getTenantStatementReport,
  normalizeOwnerStatementReport,
  normalizeTenantStatementReport,
  type OwnerStatementReport,
  type OwnerStatementTransaction,
  type TenantStatementLine,
  type TenantStatementReport,
} from './statements-reports-service';
export {
  getCashFlowStatementReport,
  getVatReturnReport,
  normalizeCashFlowStatementReport,
  normalizeVatReturnReport,
  type CashFlowStatementReport,
  type ReportPeriod,
  type StatementReportFilters,
  type VatReturnReport,
} from './financial-statements-service';
export {
  getAgedReceivablesReport,
  getArrearsSummaryReport,
  getDashboardArrearsReports,
  getOverdueInvoicesReport,
  calculateDaysOverdue,
  filterInvoicesForArrearsReport,
  getAgingBucketKey,
  summarizeAgedReceivablesReport,
  summarizeArrearsSummaryReport,
  summarizeOverdueInvoicesReport,
  type AgedReceivablesBucket,
  type AgedReceivablesGroupRow,
  type AgedReceivablesReport,
  type AgingBucketKey,
  type ArrearsReportFilters,
  type ArrearsSummaryReport,
  type DashboardArrearsReports,
  type OverdueInvoiceReportRow,
  type OverdueInvoicesReport,
} from './arrears-reports-service';
export {
  filterExpensesForReport,
  filterInvoicesForReport,
  filterPaymentsForReport,
  getCollectionSummaryReport,
  getDailyCollectionReport,
  getExpenseBreakdownReport,
  getExpenseTotalsReport,
  getFinancialCashflowReport,
  getFinancialPeriodSummaryReport,
  getInvoiceTotalsReport,
  getOutstandingBalanceReport,
  getPaymentTotalsReport,
  summarizeCollectionReport,
  summarizeDailyCollectionReport,
  summarizeExpenseBreakdownReport,
  summarizeExpenseTotals,
  summarizeFinancialCashflowReport,
  summarizeFinancialPeriodSummaryReport,
  summarizeInvoiceTotals,
  summarizeOutstandingBalance,
  summarizePaymentTotals,
  type CollectionSummaryReport,
  type DailyCollectionReport,
  type DailyCollectionReportRow,
  type ExpenseBreakdownCategoryRow,
  type ExpenseBreakdownPropertyRow,
  type ExpenseBreakdownReport,
  type ExpenseBreakdownReportFilters,
  type ExpenseTotalsReport,
  type FinancialCashflowReport,
  type FinancialCashflowReportRow,
  type FinancialPeriodSummaryReport,
  type FinancialReportFilters,
  type FinancialReportStatus,
  type InvoiceTotalsReport,
  type OutstandingBalanceReport,
  type PaymentMethodTotals,
  type PaymentTotalsReport,
} from './operational-collection-service';
