// Compatibility facade for the remaining supported financial-report surface.
// Domain implementations live in focused modules below; retired loaders are
// removed instead of being kept alive through this facade.
export {
  getBalanceSheetReport,
  getIncomeStatementReport,
  getTrialBalanceReport,
  type BalanceSheetReport,
  type BalanceSheetSectionItem,
  type IncomeStatementLine,
  type IncomeStatementReport,
  type TrialBalanceAccount,
  type TrialBalanceReport,
} from '@/features/accounting/reports/accountingReportsFacade';

export {
  getOwnerStatementReport,
  getTenantStatementReport,
  normalizeOwnerStatementReport,
  normalizeTenantStatementReport,
  type OwnerStatementReport,
  type OwnerStatementTransaction,
  type TenantStatementLine,
  type TenantStatementReport,
} from './statements-reports-service';
export {
  getVatReturnReport,
  normalizeCashFlowStatementReport,
  normalizeVatReturnReport,
  type CashFlowStatementReport,
  type ReportPeriod,
  type StatementReportFilters,
  type VatReturnReport,
} from './financial-statements-service';
export {
  getAgedReceivablesReport,
  getArrearsSummaryReport,
  getDashboardArrearsReports,
  getOverdueInvoicesReport,
  calculateDaysOverdue,
  filterInvoicesForArrearsReport,
  getAgingBucketKey,
  summarizeAgedReceivablesReport,
  summarizeArrearsSummaryReport,
  summarizeOverdueInvoicesReport,
  type AgedReceivablesBucket,
  type AgedReceivablesGroupRow,
  type AgedReceivablesReport,
  type AgingBucketKey,
  type ArrearsReportFilters,
  type ArrearsSummaryReport,
  type DashboardArrearsReports,
  type OverdueInvoiceReportRow,
  type OverdueInvoicesReport,
} from './arrears-reports-service';
export {
  filterExpensesForReport,
  filterInvoicesForReport,
  filterPaymentsForReport,
  getCollectionSummaryReport,
  getDailyCollectionReport,
  getExpenseBreakdownReport,
  getExpenseTotalsReport,
  getFinancialCashflowReport,
  getFinancialPeriodSummaryReport,
  getInvoiceTotalsReport,
  getOutstandingBalanceReport,
  getPaymentTotalsReport,
  getPropertyCollectionBreakdownReport,
  summarizeCollectionReport,
  summarizeDailyCollectionReport,
  summarizeExpenseBreakdownReport,
  summarizeExpenseTotals,
  summarizeFinancialCashflowReport,
  summarizeFinancialPeriodSummaryReport,
  summarizeInvoiceTotals,
  summarizeOutstandingBalance,
  summarizePaymentTotals,
  summarizePropertyCollectionBreakdownReport,
  type CollectionSummaryReport,
  type DailyCollectionReport,
  type DailyCollectionReportRow,
  type ExpenseBreakdownCategoryRow,
  type ExpenseBreakdownPropertyRow,
  type ExpenseBreakdownReport,
  type ExpenseBreakdownReportFilters,
  type ExpenseTotalsReport,
  type FinancialCashflowReport,
  type FinancialCashflowReportRow,
  type FinancialPeriodSummaryReport,
  type FinancialReportFilters,
  type FinancialReportStatus,
  type InvoiceTotalsReport,
  type OutstandingBalanceReport,
  type PaymentMethodTotals,
  type PaymentTotalsReport,
  type PropertyCollectionBreakdownReport,
  type PropertyCollectionBreakdownRow,
} from './financial-reporting';
