import type { AutomationRule, AutomationTemplatePreview } from './types';

/**
 * Product UI catalog for the Automation Center.
 * Backend job execution is intentionally deferred; this catalog is the
 * expandable contract for future workers and notification providers.
 */
export const automationRulesCatalog: readonly AutomationRule[] = [
  {
    id: 'contract-expiry-30',
    name: 'تذكير انتهاء العقود (30 يوماً)',
    description: 'معاينة رسالة للمستأجر قبل انتهاء العقد؛ لا توجد قناة واتساب حية.',
    category: 'contracts',
    channel: 'whatsapp',
    status: 'paused',
    frequency: 'daily',
    triggerLabel: 'عقد ينتهي خلال 30 يوماً',
    audienceLabel: 'المستأجر والمالك ومدير المحفظة',
    lastRunAt: null,
    nextRunAt: null,
    successRate: 0,
  },
  {
    id: 'contract-expiry-7',
    name: 'تذكير انتهاء العقود (7 أيام)',
    description: 'تنبيه عاجل قبل أسبوع من نهاية العقد مع اقتراح مسار التجديد.',
    category: 'contracts',
    channel: 'in_app',
    status: 'active',
    frequency: 'daily',
    triggerLabel: 'عقد ينتهي خلال 7 أيام',
    audienceLabel: 'فريق التشغيل',
    lastRunAt: null,
    nextRunAt: null,
    successRate: 100,
  },
  {
    id: 'rent-reminder-due',
    name: 'تذكير استحقاق الإيجار',
    description: 'معاينة تذكير قبل الاستحقاق؛ تتطلب موافقة ومراجعة بشرية ولا تُرسل تلقائياً.',
    category: 'rent',
    channel: 'whatsapp',
    status: 'paused',
    frequency: 'daily',
    triggerLabel: 'فاتورة مستحقة خلال 3 أيام',
    audienceLabel: 'المستأجر',
    lastRunAt: null,
    nextRunAt: null,
    successRate: 0,
  },
  {
    id: 'rent-overdue-escalation',
    name: 'تصعيد المتأخرات',
    description: 'تنبيه تصعيدي بعد 7 أيام من التأخر مع نسخة تشغيلية للمتابعة.',
    category: 'collections',
    channel: 'email',
    status: 'paused',
    frequency: 'daily',
    triggerLabel: 'فاتورة متأخرة أكثر من 7 أيام',
    audienceLabel: 'المستأجر + مسؤول التحصيل',
    lastRunAt: null,
    nextRunAt: null,
    successRate: 94,
  },
  {
    id: 'owner-monthly-report',
    name: 'تقرير المالك الشهري',
    description: 'ملخص تحصيل ومصروفات وإشغال يُجهَّز نهاية كل شهر.',
    category: 'owners',
    channel: 'email',
    status: 'draft',
    frequency: 'monthly',
    triggerLabel: 'آخر يوم عمل من الشهر',
    audienceLabel: 'الملاك النشطون',
    lastRunAt: null,
    nextRunAt: null,
    successRate: 0,
  },
  {
    id: 'maintenance-sla',
    name: 'تنبيهات الصيانة',
    description: 'تنبيه عند تجاوز طلب صيانة المفتوحة لمدة محددة دون حل.',
    category: 'maintenance',
    channel: 'in_app',
    status: 'active',
    frequency: 'daily',
    triggerLabel: 'طلب مفتوح أكثر من 48 ساعة',
    audienceLabel: 'فريق الصيانة',
    lastRunAt: null,
    nextRunAt: null,
    successRate: 97,
  },
] as const;

export const automationTemplatePreviews: readonly AutomationTemplatePreview[] = [
  {
    id: 'tpl-rent-reminder',
    title: 'تذكير إيجار',
    channel: 'whatsapp',
    body: 'هذا تذكير عام بوجود استحقاق قادم. تحقق من السجل أو تواصل مع المكتب عبر القناة المعتمدة.',
  },
  {
    id: 'tpl-contract-expiry',
    title: 'تجديد عقد',
    channel: 'whatsapp',
    body: 'يوجد عقد يقترب من نهايته. راجع ملف العقد قبل بدء أي إجراء تجديد.',
  },
  {
    id: 'tpl-overdue-escalation',
    title: 'تصعيد متأخرات',
    channel: 'whatsapp',
    body: 'يوجد استحقاق يحتاج متابعة. تحقق من السجل المعتمد قبل الرد أو السداد.',
  },
  {
    id: 'tpl-owner-report',
    title: 'تقرير مالك',
    channel: 'email',
    body: 'أصبح ملخص دوري جاهزاً للمراجعة عبر المسار المعتمد. لا تعتمد على معاينة الرسالة ككشف حساب.',
  },
  {
    id: 'tpl-maintenance-alert',
    title: 'تنبيه صيانة',
    channel: 'in_app',
    body: 'يوجد طلب صيانة يحتاج متابعة داخل MALEK.',
  },
] as const;
