import type { AutomationRule, AutomationTemplatePreview } from './types';

/**
 * Product UI catalog for the Automation Center.
 * Backend job execution is intentionally deferred; this catalog is the
 * expandable contract for future workers and notification providers.
 */
export const automationRulesCatalog: readonly AutomationRule[] = [
  {
    id: 'contract-expiry-30',
    name: 'تذكير انتهاء العقود (30 يوماً)',
    description: 'إشعار داخل النظام ورسالة للمستأجر/المالك قبل انتهاء العقد بثلاثين يوماً.',
    category: 'contracts',
    channel: 'whatsapp',
    status: 'active',
    frequency: 'daily',
    triggerLabel: 'عقد ينتهي خلال 30 يوماً',
    audienceLabel: 'المستأجر والمالك ومدير المحفظة',
    lastRunAt: null,
    nextRunAt: null,
    successRate: 100,
  },
  {
    id: 'contract-expiry-7',
    name: 'تذكير انتهاء العقود (7 أيام)',
    description: 'تنبيه عاجل قبل أسبوع من نهاية العقد مع اقتراح مسار التجديد.',
    category: 'contracts',
    channel: 'in_app',
    status: 'active',
    frequency: 'daily',
    triggerLabel: 'عقد ينتهي خلال 7 أيام',
    audienceLabel: 'فريق التشغيل',
    lastRunAt: null,
    nextRunAt: null,
    successRate: 100,
  },
  {
    id: 'rent-reminder-due',
    name: 'تذكير استحقاق الإيجار',
    description: 'إرسال تذكير قبل تاريخ الاستحقاق بثلاثة أيام.',
    category: 'rent',
    channel: 'whatsapp',
    status: 'active',
    frequency: 'daily',
    triggerLabel: 'فاتورة مستحقة خلال 3 أيام',
    audienceLabel: 'المستأجر',
    lastRunAt: null,
    nextRunAt: null,
    successRate: 98,
  },
  {
    id: 'rent-overdue-escalation',
    name: 'تصعيد المتأخرات',
    description: 'تنبيه تصعيدي بعد 7 أيام من التأخر مع نسخة تشغيلية للمتابعة.',
    category: 'collections',
    channel: 'email',
    status: 'paused',
    frequency: 'daily',
    triggerLabel: 'فاتورة متأخرة أكثر من 7 أيام',
    audienceLabel: 'المستأجر + مسؤول التحصيل',
    lastRunAt: null,
    nextRunAt: null,
    successRate: 94,
  },
  {
    id: 'owner-monthly-report',
    name: 'تقرير المالك الشهري',
    description: 'ملخص تحصيل ومصروفات وإشغال يُجهَّز نهاية كل شهر.',
    category: 'owners',
    channel: 'email',
    status: 'draft',
    frequency: 'monthly',
    triggerLabel: 'آخر يوم عمل من الشهر',
    audienceLabel: 'الملاك النشطون',
    lastRunAt: null,
    nextRunAt: null,
    successRate: 0,
  },
  {
    id: 'maintenance-sla',
    name: 'تنبيهات الصيانة',
    description: 'تنبيه عند تجاوز طلب صيانة المفتوحة لمدة محددة دون حل.',
    category: 'maintenance',
    channel: 'in_app',
    status: 'active',
    frequency: 'daily',
    triggerLabel: 'طلب مفتوح أكثر من 48 ساعة',
    audienceLabel: 'فريق الصيانة',
    lastRunAt: null,
    nextRunAt: null,
    successRate: 97,
  },
] as const;

export const automationTemplatePreviews: readonly AutomationTemplatePreview[] = [
  {
    id: 'tpl-rent-reminder',
    title: 'تذكير إيجار',
    channel: 'whatsapp',
    body: 'مرحباً {{tenant_name}}، تذكير بأن إيجار وحدة {{unit_number}} يستحق بتاريخ {{due_date}}. المبلغ: {{amount}}.',
  },
  {
    id: 'tpl-contract-expiry',
    title: 'تجديد عقد',
    channel: 'whatsapp',
    body: 'عقدكم على {{property_title}} / {{unit_number}} ينتهي بتاريخ {{end_date}}. يسعدنا ترتيب التجديد.',
  },
  {
    id: 'tpl-owner-report',
    title: 'تقرير مالك',
    channel: 'email',
    body: 'ملخص شهر {{month}}: التحصيل {{collected}}، المصروفات {{expenses}}، صافي {{net}}، نسبة الإشغال {{occupancy}}%.',
  },
  {
    id: 'tpl-maintenance-alert',
    title: 'تنبيه صيانة',
    channel: 'in_app',
    body: 'طلب الصيانة {{ticket_title}} ما زال مفتوحاً منذ {{open_hours}} ساعة ويتطلب متابعة.',
  },
] as const;
