import { EntityPreviewDialog } from '@/components/ui/entity-preview-dialog';
import { ContextualDocumentsSection } from '@/components/documents/contextual-documents-section';
import { DetailFields } from '@/components/ui/detail-fields';
import { StatusBadge } from '@/components/ui/status-badge';
import type { TenantWorkspaceRow } from '../tenantWorkspaceService';

export function TenantPreviewDialog({ tenant, open, onOpenChange, onEdit }: Readonly<{ tenant: TenantWorkspaceRow | null; open: boolean; onOpenChange: (open: boolean) => void; onEdit: (personId: string) => void }>) {
  return <EntityPreviewDialog open={open} onOpenChange={onOpenChange} title={tenant?.person.full_name ?? 'معاينة المستأجر'} description="ملف المستأجر وعقده وسياقه التشغيلي بدون مغادرة سجل المستأجرين" actions={tenant ? <button type="button" className="min-h-11 rounded-xl bg-primary px-4 text-sm font-bold text-primary-foreground" onClick={() => onEdit(tenant.person.id)}>تعديل</button> : undefined}>
    {tenant ? <div className="space-y-5"><section className="rounded-2xl border border-border/70 bg-card p-5"><h3 className="mb-4 text-base font-black">البيانات الأساسية</h3><DetailFields columns={3} fields={[{ label: 'الاسم', value: tenant.person.full_name }, { label: 'الهاتف', value: tenant.person.phone ? <span dir="ltr">{tenant.person.phone}</span> : 'غير موثق' }, { label: 'البريد', value: tenant.person.email ? <span dir="ltr">{tenant.person.email}</span> : 'غير موثق' }, { label: 'رقم الهوية', value: tenant.person.national_id ?? 'غير موثق' }, { label: 'العقار', value: tenant.propertyTitle ?? 'غير محدد' }, { label: 'الوحدة', value: tenant.unitNumber ?? 'غير محددة' }]} /></section><section className="rounded-2xl border border-border/70 bg-card p-5"><h3 className="mb-3 text-base font-black">الحالة والعلاقات</h3><div className="flex flex-wrap gap-2"><StatusBadge tone={tenant.activeContractCount > 0 ? 'success' : 'neutral'}>{tenant.activeContractCount > 0 ? `${tenant.activeContractCount} عقد نشط` : 'لا يوجد عقد نشط'}</StatusBadge>{tenant.hasInvoices ? <StatusBadge tone="info">لديه فواتير</StatusBadge> : null}{tenant.hasArrears ? <StatusBadge tone="warning">لديه متأخرات</StatusBadge> : null}</div><p className="mt-3 text-sm leading-6 text-muted-foreground">العقد الأساسي: {tenant.primaryContractId ?? 'غير محدد'} — يمكن فتح التفاصيل المالية من واجهة الفواتير التشغيلية.</p></section><ContextualDocumentsSection entityType="tenant" entityId={tenant.person.id} entityLabel="المستأجر" /></div> : null}
  </EntityPreviewDialog>;
}
